### ISSUE TITLE
consistant font style - single type of font should be used 

### ISSUE THREAD

**Issue by ravichanga101** [ravichanga101/CSPIT_NEW_2024#13]

**Comment by Vatsal2054** [comment]
These two open source font styles are the best choice for us:

## 1. Mona Sans by Github 
### Mona sans is very flexible and can support many font styles.
![Mona-sans-preview](https://github.com/user-attachments/assets/f07eb936-1eee-49df-a81e-27a94e96dad1)


## 2. Inter
### Inter is not much flexible but is widely used.
![Inter-preview](https://github.com/user-attachments/assets/67d0274b-67a7-4fff-9e19-a252f70fc863)

**Comment by ravichanga101** [comment]
Mona sans is a good choice

**Comment by Vatsal2054** [comment]
OK, I will start working on that.
