### ISSUE TITLE
Suggestions given in meeting - 14-10-2024

### ISSUE THREAD

**Issue by Jalpeshv** [ravichanga101/CSPIT_NEW_2024#2]
- 5 HD images in slider
- Scalar digit font size should be increased, and animation should be added.
- Remove the yellow colour underline from each section title.
Keep the card view of the first line(without description) for courses like Computer engineering/IT/ME/CL, etc. Also, use Unsplash for stock images(without copyright).
- Academia Partner cards should be displayed separately.
- Add Students Club, with logos.
- All section titles are in Uppercase.
- Change the opacity of the menu to look like little bit transparent.
- Set an image of the faculty on the Faculty profile page.
- Announcement Section to be added.
- Gallery Section to be added with tabs/pills/buttons with titles like Events.
- on the profile page keep the following details in each faculty -Academics, Research & Publication, Projects
- on the profile page, add a globe symbol to add an individual website (preferably Vidwan), orchid, or Google Scholar symbol.
- remove the profile title
- Add email after their qualification in jv[at]charusat[dot]com format.

**Comment by Kabir0809** [comment]
Announcement Section is pending for design approval
