### ISSUE TITLE
color of all sections should be consistant

### ISSUE THREAD

**Issue by ravichanga101** [ravichanga101/CSPIT_NEW_2024#8]

**Comment by Vatsal2054** [comment]
# Color palette:

### I think we should follow this color palette:
- Blue and Orange as theme colors.
- White for background.
- Dark grey for font. (Avoiding pure black as it increases the contrast)

![CSPIT_color_palette](https://github.com/user-attachments/assets/49a9e10b-71bd-4474-aec6-e00a09ebe0d3)

**Comment by ravichanga101** [comment]
Yes , good choice 👍 

How can differentiate sections?

**Comment by Vatsal2054** [comment]
We can differentiate them by their backgrounds. White color will be the primary component but we will experiment with different background ideas such as,
- Gradients on theme color
- Images

and Visual breakpoints such as bold headers, etc.
