### ISSUE TITLE
Content Sequence of the Main Page

### ISSUE THREAD

**Issue by Jalpeshv** [ravichanga101/CSPIT_NEW_2024#92]
About CSPIT,
Programs Offered,
Industry recognized Courses,
Student/Profession chapters
Student Clubs
Student projects
Scalars
Research Thrust Area,
From Dean's and Principal's Desk
Testimonials

**Comment by Kabir0809** [comment]
Where to put CSPIT MOU section, gallery section and announcement section (announcement in top bar would be difficult as VIT website does not have quick menu where as we have so suggest about it).
